baseurl = "http://blog.fntlnz.wtf"
languageCode = "en-us"
title = "fntlnz's blog"
theme = "fntlnz"
paginate = 500
PygmentsCodeFences = true
PygmentsOptions = "linenos=table"
PygmentsStyle = "bw"
disqusShortname = "fntlnz"
googleAnalytics = "UA-45983436-3"

